### product-api calls

###get all products
GET http://localhost:4000/product-api/products

### create a product
POST http://localhost:4000/product-api/products
Content-Type: application/json

{
    "productName": "Shirt",
    "price": 2000,
    "brand": "Nike"
}

###get product by id
GET http://localhost:4000/product-api/products/6981a5e514774193da106d43

### delete product by id
DELETE http://localhost:4000/product-api/products/6981a5e514774193da106d43

### get products by brand
GET http://localhost:4000/product-api/product-brand/Puma


### user-api calls

### create a user
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "name":"karthik",
    "email":"karthik@gmail.com",
    "password":"karthik123",
    "cart":[]
}

### request to add product to cart
PUT http://localhost:4000/user-api/user-cart/user-id/698e158350bcb288364ca2ac/product-id/698e143dd234313fcfebe33c

### get user by id
GET http://localhost:4000/user-api/user-id/698e158350bcb288364ca2ac

### get all users
GET http://localhost:4000/user-api/users

### delete user by id
DELETE  http://localhost:4000/user-api/user-delete/69833914291ad2092c41d4d4